### ISSUE TITLE
Forum "Posted By" username should be matching font yellow

### ISSUE THREAD

**Issue by physics515** [physics515/hiveFive.life#10]
See below for notable instances on the forum index page:
![capture3](https://user-images.githubusercontent.com/7359379/32478794-49915c70-c34c-11e7-897e-101ba65d2b34.PNG)

**Comment by sick115** [comment]
I left the special users their default colors. I thought it would be a good idea to be able to tell who is an admin, mod, etc. Maybe pick different colors than the defaults? What do you think? Regular users should have the default yellow.

**Comment by physics515** [comment]
I would use "Turbo" #FFC920 as the admin name color, and maybe "Golden Brown" #865E00 & "Grandis" #FFCF6E for other groups in the future.
