### ISSUE TITLE
Forum Login textboxes and "Login" button should be matching buttons style on the main-site.

### ISSUE THREAD

**Issue by physics515** [physics515/hiveFive.life#11]
See below for prominent instances on the forum index page.
![capture](https://user-images.githubusercontent.com/7359379/32478932-fd8863ea-c34c-11e7-8181-29a027162abf.PNG)

**Comment by sick115** [comment]
Text box background is transparent yellow with dark text. Login button is the opposite.

TO DO:
 -The login button shows a white background on hover
 -The "Remember me" checkbox isn't colored correctly.

**Comment by physics515** [comment]
Preferred action would be that the BG-color stays the same and the text color changes from "Sweet Corn" #FFE57A to "Turbo" #FFC920, to show emphasis.

**Comment by physics515** [comment]
Issue is still open:

![capture](https://user-images.githubusercontent.com/7359379/33868831-f716b054-deca-11e7-85e1-ec93b4d880a5.PNG)

**Comment by physics515** [comment]
Revamped forum with new theme, this is no longer relevant.
