### ISSUE TITLE
Forum footer should be locked to bottom of page.

### ISSUE THREAD

**Issue by physics515** [physics515/hiveFive.life#15]
The forum footer should be docked to the bottom of the page, similar to the "Vote!" button on the main-site. This should be separated by a 1px top-border above the footer (#FFC90D). 

See below for reference:
![capture](https://user-images.githubusercontent.com/7359379/32479327-e209fe1a-c34e-11e7-8fc8-99a349df0887.PNG)
![capture1](https://user-images.githubusercontent.com/7359379/32479328-e3048754-c34e-11e7-84a6-0735f48f0c22.PNG)

**Comment by sick115** [comment]
Footer locked to bottom, border not in place yet.

**Comment by sick115** [comment]
Changed to work on mobile devices.

**Comment by physics515** [comment]
Footer is below the window (you have to scroll to see it) on desktop.

**Comment by physics515** [comment]
This will take a little more work to make it right. Use below tutorial as a guide:
[How to keep footers at the bottom of the page](http://matthewjamestaylor.com/blog/keeping-footers-at-the-bottom-of-the-page)

**Comment by physics515** [comment]
complete.
