### ISSUE TITLE
Remove "Powered by phpBB" text.

### ISSUE THREAD

**Issue by physics515** [physics515/hiveFive.life#16]
Remove below text from forum footer:
![capture](https://user-images.githubusercontent.com/7359379/32479385-33196386-c34f-11e7-9526-9efa308980b4.PNG)

Replace with "Copyright &copy; 2017-2018 hiveFive.life".

**Comment by sick115** [comment]
Replaced copyright text to specified. If changes aren't showing, purge the cache in the Administrative Control Panel - General tab.
