### ISSUE TITLE
Remove forum permissions section from post page.

### ISSUE THREAD

**Issue by physics515** [physics515/hiveFive.life#18]
See below for referred section:

![capture](https://user-images.githubusercontent.com/7359379/32533023-cf3e7ff2-c413-11e7-8915-21bd1d2184a8.PNG)
 
![capture](https://user-images.githubusercontent.com/7359379/32532994-a42b8b16-c413-11e7-9dbe-05a3de679670.PNG)

**Comment by sick115** [comment]
Removed forum permissions section.
