### ISSUE TITLE
Implement coinhive captcha in the forum wherever captcha is used.

### ISSUE THREAD

**Issue by physics515** [physics515/hiveFive.life#23]
Replace all instances of this:
![capture1](https://user-images.githubusercontent.com/7359379/32586207-f18a32a0-c4c6-11e7-92e6-e96326d5e52f.PNG)

With this:
![capture](https://user-images.githubusercontent.com/7359379/32586212-f8197bc6-c4c6-11e7-8861-d4a05528a87a.PNG)

**Comment by pedromaestu** [comment]
Good job :-) Use coinhive was looking for something like that to pay directly to the users :-)
I would like to install it possible thanks

**Comment by physics515** [comment]
I apologize, this issue should have already been closed. Our forum is no longer part of our github repo. Do you have experience with installing coinhive captcha in phpBB forums?
