### ISSUE TITLE
Add forum button to main site.

### ISSUE THREAD

**Issue by physics515** [physics515/hiveFive.life#3]
There should be a discussion about how we implement the forum into the site. Should we take the approach of implementing an Ajax solution and bringing in only the elements that we want. Or for the sake of ease and time should we continue on the current path of removing and re-theming the stock phpBB forum.

I believe the Ajax approach is the optimally desired rout, and what I would like to see in the end final product but I also feel that as we are pressed for time that we should focus on producing a minimally viable product. This discussion should take place before we should proceed with modifying the forum theme.

Please comment here with your thoughts.

**Comment by sick115** [comment]
Ajax would be optimal,  I agree.  But if we're pressed for time,  then I don't see why it would be too big an issue to not use it.

**Comment by physics515** [comment]
I agree. I say that we proceed with making the updates to the forum as we are. Until we hit the "Beta" milestone set for January 15th. After we have the site up and running and the kickstarter campaign going then we can focus on an Ajax implementation.

**Comment by sick115** [comment]
If being able to mine while browsing the forums is a priority, we can force a new tab as a placeholder, then add Ajax later.

**Comment by physics515** [comment]
Agreed. I'll add a button to the main page this week that links to the forums and forces a new tab.
