### ISSUE TITLE
Format search bar at top of forum.

### ISSUE THREAD

**Issue by physics515** [physics515/hiveFive.life#8]
![capture](https://user-images.githubusercontent.com/7359379/32477877-05a9b836-c347-11e7-82cb-7c77d0ed4e96.PNG)

This should match the look of the rest of the site. The "Search Settings" button should be removed and the "Hourglass" should be replaced with a button that matched the style throughout the site.

**Comment by physics515** [comment]
Of course that glow around it should go away too.

**Comment by sick115** [comment]
Reformatted to match colors. Still need to adjust it to make it a "box", but I kind of like how it is right now. Thoughts?

TO DO:
-Remove settings button

**Comment by sick115** [comment]
Removed the settings button.

**Comment by physics515** [comment]
![capture](https://user-images.githubusercontent.com/7359379/32532623-2f5610a6-c411-11e7-8e6a-32124208aeeb.PNG)

This looks much better but lets remove the rounded border and make it a rectangle 1px thick border in color,  "Turbo" #FFC920.

**Comment by sick115** [comment]
I could've sworn that that extra box had been removed

**Comment by physics515** [comment]
Revamped forum with new style, this issue is no longer relevant.
