### ISSUE TITLE
Dark grey text on forum should be matching the yellow text.

### ISSUE THREAD

**Issue by physics515** [physics515/hiveFive.life#9]
See bellow for several notable instances on the forum index page:
![capture](https://user-images.githubusercontent.com/7359379/32478728-05c62cb4-c34c-11e7-8018-c02df8887ed6.PNG)
![capture1](https://user-images.githubusercontent.com/7359379/32478729-05dae410-c34c-11e7-9d25-7bb2a8faabe5.PNG)
![capture2](https://user-images.githubusercontent.com/7359379/32478730-05efe57c-c34c-11e7-88fb-aff56f73ea6b.PNG)
![capture3](https://user-images.githubusercontent.com/7359379/32478731-0601ea88-c34c-11e7-895f-c87fa700c5d6.PNG)

**Comment by sick115** [comment]
All text, including text input into forms, should match the yellow.  I left special username texts (admin, moderator, etc.) their default colors so it is easy to differentiate between them. If you find any that needs to be changed let me know. As far as I can find, it all looks right.
